/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import MUNDO.Monopoly;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author JulianOlarte
 */
public class InfoJugador extends javax.swing.JFrame {

    /**
     * Creates new form InfoJugador
     */
    private JButton boton;
    private Monopoly m;
    public InfoJugador(Monopoly m,JButton boton) {
        initComponents();
       this.setLocationRelativeTo(null);
        this.boton=boton;
        this.m=m;
        Color col = null;
        if("1".equals(this.boton.getText()))
        {
            col=new Color(202,0,0);
        }
        else if("2".equals(this.boton.getText()))
        {
            col=new Color(0,64,128);
        } 
        else if("3".equals(this.boton.getText()))
        {
            col=new Color(0,100,0);   
        }
        else if("4".equals(this.boton.getText()))
        {
            col=new Color(255,45,45);   
        }
        this.jLabel1.setText("JUGADOR "+this.boton.getText());
        this.jpanelborde.setBackground(col);
        this.jbuteliminar.setBackground(col);
        this.jbutcerrar.setBackground(col);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelborde = new javax.swing.JPanel();
        jpanel = new javax.swing.JPanel();
        jbuteliminar = new javax.swing.JButton();
        jbutcerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jpanelborde.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jpanel.setBackground(new java.awt.Color(255, 255, 255));
        jpanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jbuteliminar.setBackground(new java.awt.Color(0, 0, 160));
        jbuteliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbuteliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbuteliminar.setText("Eliminar Jugador");
        jbuteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuteliminarActionPerformed(evt);
            }
        });

        jbutcerrar.setBackground(new java.awt.Color(0, 0, 160));
        jbutcerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbutcerrar.setForeground(new java.awt.Color(255, 255, 255));
        jbutcerrar.setText("Cerrar");
        jbutcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutcerrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
        jpanel.setLayout(jpanelLayout);
        jpanelLayout.setHorizontalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jbuteliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jbutcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jpanelLayout.setVerticalGroup(
            jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuteliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout jpanelbordeLayout = new javax.swing.GroupLayout(jpanelborde);
        jpanelborde.setLayout(jpanelbordeLayout);
        jpanelbordeLayout.setHorizontalGroup(
            jpanelbordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelbordeLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jpanelbordeLayout.setVerticalGroup(
            jpanelbordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelbordeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelborde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelborde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutcerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbutcerrarActionPerformed

    private void jbuteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuteliminarActionPerformed
        this.boton.setVisible(false);
        JButton eliminado=this.m.eliminarJugador(Integer.parseInt(this.boton.getText()));
        
        
        this.dispose();
    }//GEN-LAST:event_jbuteliminarActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbutcerrar;
    private javax.swing.JButton jbuteliminar;
    private javax.swing.JPanel jpanel;
    private javax.swing.JPanel jpanelborde;
    // End of variables declaration//GEN-END:variables
}
