/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import MUNDO.Monopoly;
import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/** 
 *
 * @author JulianOlarte
 */
public class Tablero extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Tablero
     */ 
    
    private JPanelF panel;
   private Monopoly m;
   private int[] dados;
   private JFrame principal;
   private int x,y;
   
    public Tablero(Monopoly m, JFrame principal) {
        this.principal=principal;
        this.m=m;
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(0,64,128));
        panel=new JPanelF("/IMAGENES/board.png",m,this.jbutavanzar,this.jtxtturno);
        panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        panel.setLayout(null);
        panel.setBounds(0,0,700,700);
        
        this.jbutavanzar.setBackground(new Color(0,64,128));
        this.jbutreiniciar.setBackground(new Color(0,64,128));
        this.add(panel);
        
        
        
        
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelcontroles = new javax.swing.JPanel();
        jtxtturno2 = new javax.swing.JLabel();
        jtxtturno = new javax.swing.JLabel();
        jbutavanzar = new javax.swing.JButton();
        jlabel1 = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        jbutreiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        jpanelcontroles.setBackground(new java.awt.Color(255, 255, 255));
        jpanelcontroles.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jtxtturno2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jtxtturno2.setText("TURNO JUGADOR ");

        jtxtturno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jtxtturno.setText("1");

        jbutavanzar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jbutavanzar.setForeground(new java.awt.Color(255, 255, 255));
        jbutavanzar.setText("TIRAR DADOS");
        jbutavanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutavanzarActionPerformed(evt);
            }
        });

        jlabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/dado6.png"))); // NOI18N

        jbutreiniciar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jbutreiniciar.setForeground(new java.awt.Color(255, 255, 255));
        jbutreiniciar.setText("VOLVER");
        jbutreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutreiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelcontrolesLayout = new javax.swing.GroupLayout(jpanelcontroles);
        jpanelcontroles.setLayout(jpanelcontrolesLayout);
        jpanelcontrolesLayout.setHorizontalGroup(
            jpanelcontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelcontrolesLayout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(jpanelcontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelcontrolesLayout.createSequentialGroup()
                        .addGroup(jpanelcontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelcontrolesLayout.createSequentialGroup()
                                .addComponent(jtxtturno2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtturno, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelcontrolesLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jpanelcontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbutavanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbutreiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelcontrolesLayout.createSequentialGroup()
                        .addComponent(jlabel1)
                        .addGap(83, 83, 83))))
        );
        jpanelcontrolesLayout.setVerticalGroup(
            jpanelcontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelcontrolesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpanelcontrolesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtturno2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtturno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbutavanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addComponent(jbutreiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(715, Short.MAX_VALUE)
                .addComponent(jpanelcontroles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelcontroles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutavanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutavanzarActionPerformed
    this.jbutavanzar.setEnabled(false);
        Random rn=new Random();
    int n=0;
    int dado=1;
    int[] d=new int[15];
    while(n<15)
    {
        dado=rn.nextInt(6)+1;
        d[n]=dado;
        n++;
    }
      this.dados=d;
      Thread hilo=new Thread(this);
      hilo.start();
    }//GEN-LAST:event_jbutavanzarActionPerformed

    private void jbutreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutreiniciarActionPerformed
        principal.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_jbutreiniciarActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        this.x=evt.getX();
        this.y=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
          Point point = MouseInfo.getPointerInfo().getLocation()   ; 
           setLocation(point.x - x, point.y - y)   ;
    }//GEN-LAST:event_formMouseDragged

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbutavanzar;
    private javax.swing.JButton jbutreiniciar;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JPanel jpanelcontroles;
    private javax.swing.JLabel jtxtturno;
    private javax.swing.JLabel jtxtturno2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        try {
            int n=0;
            AudioClip sonido=Applet.newAudioClip(getClass().getResource("/AUDIO/diceshuffle.wav"));
            AudioClip sonido2=Applet.newAudioClip(getClass().getResource("/AUDIO/dicethrow.wav"));
            sonido.play();
            
               while(n<dados.length)
               {
                   if(dados[n]==1)
                   {
                       this.jlabel1.setIcon(new ImageIcon(this.getClass().getResource("/IMAGENES/dado1.png")));
                   }
                   else if(dados[n]==2)
                   {
                       this.jlabel1.setIcon(new ImageIcon(this.getClass().getResource("/IMAGENES/dado2.png")));
                   }
                   else if(dados[n]==3)
                   {
                       this.jlabel1.setIcon(new ImageIcon(this.getClass().getResource("/IMAGENES/dado3.png")));
                   }
                   else if(dados[n]==4)
                   {
                       this.jlabel1.setIcon(new ImageIcon(this.getClass().getResource("/IMAGENES/dado4.png")));
                   }
                   else if(dados[n]==5)
                   {
                       this.jlabel1.setIcon(new ImageIcon(this.getClass().getResource("/IMAGENES/dado5.png")));
                   }
                   else if(dados[n]==6)
                   {
                       this.jlabel1.setIcon(new ImageIcon(this.getClass().getResource("/IMAGENES/dado6.png")));
                   }
                   n++;
                   Thread.sleep(100);
                   this.repaint();
               }
               
               sonido2.play();
               Thread.sleep(1500);
               panel.setDado(dados[n-1]);
               panel.setProxcasilla((panel.getJugador().getCasilla()+dados[n-1])%24);
               panel.inicio();
               this.jlabel.setText("NUMERO OBTENIDO: "+dados[n-1]);
               Thread.sleep(1500);
        } catch (InterruptedException ex) {
            Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
}
