/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import MUNDO.Monopoly;
import MUNDO.Pregunta;
import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Color;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author JulianOlarte
 */
public class Tarjeta extends javax.swing.JFrame {

    /**
     * Creates new form Tarjeta
     */
    private JButton tirarDados,player;
    private JLabel labelturno;
    
    private Monopoly m;
    
    private JPanelF panel;
    private Pregunta pregunta;
    
    public Tarjeta(Color col,JButton tirarDados,JLabel labelturno, Monopoly m,int casilla,int valor,JPanelF panel,JButton player) {
        initComponents();
        this.jtxtarea.setLineWrap(true);
        this.jtxtarea.setWrapStyleWord(true);
        this.m=m;
        this.player=player;
        this.panel=panel;
       
        this.labelturno=labelturno;
        
         if(col.equals(Color.red))
        {
            col=new Color(202,0,0);
        }
        else if(col.equals(Color.blue))
        {
            col=new Color(0,64,128);
        }
        else if(col.equals(Color.green))
        {
            col=new Color(0,100,0);   
        }
        else if(col.equals(Color.yellow))
        {
            col=new Color(185,185,0);   
        } 
        this.tirarDados=tirarDados;
        this.jbutrespuesta.setBackground(col);
        this.jbutcerrar.setBackground(col);
        this.jpanelborde.setBackground(col);
        
        Pregunta cas6=new Pregunta("CARCEL", "HAS CAIDO EN LA CARCEL, DEBES PAGAR $20.000 DE FIANZA PARA PODER SALIR.", null, null);
        Pregunta cas12=new Pregunta("BANCO", "EL BANCO DE LA CIUDAD HA OBSERVADO QUE NO ARROJAS BASURA EN LAS CALLES, POR ESO HA DECIDIDO REGALARTE $20.000.", null, null);
        if(col.equals(Color.white))
        {
            this.jbutrespuesta.setVisible(false);
            col=Color.black;
        }
        
       
        
        this.setLocationRelativeTo(null);
        Random rn=new Random();
        
        String texto="";
        
        
        if(casilla==6)
        {
            this.pregunta=cas6;
            texto=this.pregunta.getPregunta()+"\n\nVALOR: $"+valor;
        }
        else if(casilla==12)
        {
            this.pregunta=cas12;
            texto=this.pregunta.getPregunta()+"\n\nVALOR: $"+valor;
        }
        else if(casilla==18||casilla==24)
        {
            this.pregunta=this.m.getSorpresas()[20];
            texto=this.pregunta.getPregunta();
        }
        else if(casilla==3||casilla==9||casilla==15||casilla==21)
        {
            int num=rn.nextInt(20);
            this.pregunta=this.m.getSorpresas()[num];
            texto=this.pregunta.getPregunta();
        }
        else
        {
            int num=rn.nextInt(49);
            this.pregunta=this.m.getPreguntas()[num];
            texto=this.pregunta.getPregunta()+"\n\nVALOR: $"+valor;
            
        }
        this.jtxtarea.setText(texto);
        
        if(this.pregunta.getRespuesta()==null)
        {
            this.jbutrespuesta.setVisible(false);
        }
        
        
        if(this.pregunta.getCasilla()!=null)
        {
            
            panel.setProxcasilla(this.pregunta.getCasilla());
            panel.setMovimientoExtra(1);
            
        }
        
        this.jlabeltitulo.setText(this.pregunta.getNombre());
        this.jlabeltitulo.setForeground(col);
        
        AudioClip sonido=Applet.newAudioClip(getClass().getResource("/AUDIO/cardslide.wav"));
        sonido.play();
        
    }

    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelborde = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtarea = new javax.swing.JTextArea();
        jbutrespuesta = new javax.swing.JButton();
        jbutcerrar = new javax.swing.JButton();
        jlabeltitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jpanelborde.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtxtarea.setEditable(false);
        jtxtarea.setColumns(20);
        jtxtarea.setRows(5);
        jScrollPane1.setViewportView(jtxtarea);

        jbutrespuesta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutrespuesta.setText("RESPUESTA");
        jbutrespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutrespuestaActionPerformed(evt);
            }
        });

        jbutcerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutcerrar.setText("CERRAR");
        jbutcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutcerrarActionPerformed(evt);
            }
        });

        jlabeltitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlabeltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlabeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbutrespuesta)
                        .addGap(105, 105, 105)
                        .addComponent(jbutcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jlabeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jpanelbordeLayout = new javax.swing.GroupLayout(jpanelborde);
        jpanelborde.setLayout(jpanelbordeLayout);
        jpanelbordeLayout.setHorizontalGroup(
            jpanelbordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelbordeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jpanelbordeLayout.setVerticalGroup(
            jpanelbordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelbordeLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpanelborde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelborde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutcerrarActionPerformed
        if(this.pregunta.getCasilla()!=null)
        {
            panel.setMovimientoExtra(1);
            panel.inicio();
        }
        else
        {
            this.panel.actualizarJugador();
            this.player=panel.getFicha();
           
             this.tirarDados.setEnabled(true);
            
             this.labelturno.setText(this.player.getText());
        }
       
        
        this.dispose();
    }//GEN-LAST:event_jbutcerrarActionPerformed

    private void jbutrespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutrespuestaActionPerformed
       String resp=this.jtxtarea.getText()+"\n\nRESPUESTA:\n"+this.pregunta.getRespuesta();
       this.jtxtarea.setText(resp);
       this.jbutrespuesta.setEnabled(false);
    }//GEN-LAST:event_jbutrespuestaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbutcerrar;
    private javax.swing.JButton jbutrespuesta;
    private javax.swing.JLabel jlabeltitulo;
    private javax.swing.JPanel jpanelborde;
    private javax.swing.JTextArea jtxtarea;
    // End of variables declaration//GEN-END:variables
}
